# Generated by Django 5.2.4 on 2025-08-02 09:29

import api.models.problem
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(db_column='Seq', primary_key=True, serialize=False, verbose_name='language 고유 INDEX')),
                ('language_name', models.CharField(db_column='language_name', max_length=100, verbose_name='언어이름')),
                ('version', models.CharField(db_column='version', max_length=100, verbose_name='버전')),
                ('build_command', models.TextField(db_column='build_command', verbose_name='빌드명령어')),
                ('grade_command', models.TextField(db_column='grade_command', verbose_name='채점명령어')),
                ('additional_memory', models.CharField(db_column='additional_memory', max_length=50, verbose_name='추가메모리')),
                ('additional_time', models.CharField(db_column='additional_time', max_length=50, verbose_name='추가시간')),
            ],
            options={
                'verbose_name': '언어: 언어',
                'verbose_name_plural': '언어: 언어',
                'db_table': 'language',
                'ordering': ['id', 'language_name'],
            },
        ),
        migrations.CreateModel(
            name='LanguageInChecker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(db_column='CheckkerLang', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.language', verbose_name='언어')),
            ],
            options={
                'verbose_name': '체커: 사용언어',
                'verbose_name_plural': '체커: 사용언어',
                'db_table': 'LANGUAGE_IN_CHECKER',
                'ordering': ['checker', 'language'],
            },
        ),
        migrations.CreateModel(
            name='LanguageInLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(db_column='language', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.language', verbose_name='언어')),
            ],
            options={
                'verbose_name': '수업: ',
                'verbose_name_plural': '수업: 사용언어',
                'db_table': 'LANGUAGE_IN_LECTURE',
                'ordering': ['lecture', 'language'],
            },
        ),
        migrations.CreateModel(
            name='LanguageInProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(blank=True, db_column='LANG', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.language', verbose_name='언어')),
            ],
            options={
                'verbose_name': '문제: 사용언어',
                'verbose_name_plural': '문제: 사용언어',
                'db_table': 'LANGUAGE_IN_PROBLEM',
                'ordering': ['id', 'problem'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(db_column='LectureID', primary_key=True, serialize=False, verbose_name='클래스 고유 INDEX')),
                ('lecture_name', models.CharField(db_column='Name', db_index=True, max_length=100, verbose_name='클래스이름')),
                ('description', models.TextField(blank=True, db_column='Description', default='', null=True, verbose_name='클래스 및 강의 설명')),
                ('weeks', models.IntegerField(db_column='WeekCount', default=16, verbose_name='강의 차수')),
                ('start_date', models.DateTimeField(blank=True, db_column='StartDate', null=True, verbose_name='시작기간')),
                ('end_date', models.DateTimeField(blank=True, db_column='EndDate', null=True, verbose_name='종료기간')),
                ('created_date', models.DateTimeField(auto_now=True, db_column='CDT', verbose_name='생성일')),
                ('is_delete', models.BooleanField(db_column='isDeleted', default=False, verbose_name='삭제여부')),
                ('instructor', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='담당교수 고유 INDEX')),
                ('lecture_language', models.ManyToManyField(blank=True, related_name='language', through='api.LanguageInLecture', through_fields=('lecture', 'language'), to='api.language', verbose_name='클래스 기본 언어')),
            ],
            options={
                'verbose_name': '수업: 수업',
                'verbose_name_plural': '수업: 수업',
                'db_table': 'lecture',
                'ordering': ['id', 'instructor'],
            },
        ),
        migrations.AddField(
            model_name='languageinlecture',
            name='lecture',
            field=models.ForeignKey(db_column='lecture', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.lecture', verbose_name='수업'),
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(db_column='ProblemID', primary_key=True, serialize=False, verbose_name='문제 고유 ID')),
                ('problem_name', models.CharField(db_column='ProblemName', db_index=True, default='생성중인 문제', max_length=50, verbose_name='문제이름')),
                ('description', models.TextField(blank=True, db_column='ProblemContent', default='', null=True, verbose_name='문제설명')),
                ('type', models.CharField(choices=[('PS', '솔루션'), ('PC', '체커')], db_column='ProblemType', db_index=True, default='PS', max_length=2, verbose_name='문제타입')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, '하'), (2, '중'), (3, '상')], db_column='LEV', db_index=True, default=1, verbose_name='난이도')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreateDate', verbose_name='등록일')),
                ('update_date', models.DateTimeField(auto_now=True, db_column='UpdateDate', verbose_name='수정일')),
                ('limit_time', models.IntegerField(db_column='LimitTime', verbose_name='제한시간')),
                ('limit_memory', models.IntegerField(db_column='LimitMemory', verbose_name='제한메모리')),
                ('content_path', models.TextField(blank=True, db_column='ContentFilePath', null=True, validators=[api.models.problem.validate_file_extension], verbose_name='문제설명파일')),
                ('language', models.ManyToManyField(blank=True, related_name='problem_language', through='api.LanguageInProblem', through_fields=('problem', 'language'), to='api.language', verbose_name='사용언어')),
                ('maker', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='출제자 유저 INDEX')),
            ],
            options={
                'verbose_name': '문제: 문제',
                'verbose_name_plural': '문제: 문제',
                'db_table': 'problem',
                'ordering': ['id', 'maker'],
            },
        ),
        migrations.AddField(
            model_name='languageinproblem',
            name='problem',
            field=models.ForeignKey(db_column='PROB', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.problem', verbose_name='문제'),
        ),
        migrations.CreateModel(
            name='ProblemChecker',
            fields=[
                ('id', models.BigAutoField(db_column='CheckerID', primary_key=True, serialize=False, verbose_name='체커코드 고유 INDEX')),
                ('name', models.CharField(db_column='CheckerName', max_length=20, verbose_name='체커 코드 이름')),
                ('code', models.TextField(db_column='CheckerCode', verbose_name='체커 코드 내용')),
                ('checker_language', models.ManyToManyField(blank=True, related_name='checker_language', through='api.LanguageInChecker', through_fields=('checker', 'language'), to='api.language', verbose_name='클래스 기본 언어')),
                ('problem', models.ForeignKey(db_column='ProblemID', on_delete=django.db.models.deletion.CASCADE, related_name='checker_problem', to='api.problem', verbose_name='문제 고유 ID')),
            ],
            options={
                'verbose_name': '체커코드: 체커코드',
                'verbose_name_plural': '체커코드: 체커코드',
                'db_table': 'problem_checker',
                'ordering': ['id', 'problem'],
            },
        ),
        migrations.AddField(
            model_name='languageinchecker',
            name='checker',
            field=models.ForeignKey(db_column='CheckerLang', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.problemchecker', verbose_name='체커'),
        ),
        migrations.CreateModel(
            name='ProblemInOut',
            fields=[
                ('id', models.BigAutoField(db_column='InOutID', primary_key=True, serialize=False, verbose_name='입출력 고유 INDEX')),
                ('input_code', models.TextField(db_column='Input', verbose_name='입력')),
                ('output_code', models.TextField(db_column='Output', verbose_name='출력')),
                ('problem', models.ForeignKey(db_column='ProblemID', on_delete=django.db.models.deletion.CASCADE, related_name='inout_problem', to='api.problem', verbose_name='문제 고유 INDEX')),
            ],
            options={
                'verbose_name': '문제입출력: 문제입출력',
                'verbose_name_plural': '문제입출력: 문제입출력',
                'db_table': 'problem_inout',
                'ordering': ['id', 'problem'],
            },
        ),
        migrations.CreateModel(
            name='ProblemTemplate',
            fields=[
                ('id', models.BigAutoField(db_column='TemplateID', primary_key=True, serialize=False, verbose_name='샘플코드 고유 INDEX')),
                ('template_name', models.CharField(db_column='TemplateName', default='main.cpp', max_length=100, verbose_name='샘플파일이름')),
                ('template_content', models.TextField(db_column='TemplateContent', verbose_name='파일내용')),
                ('problem', models.ForeignKey(db_column='ProblemID', on_delete=django.db.models.deletion.CASCADE, related_name='problem_template', to='api.problem', verbose_name='문제 고유 INDEX')),
            ],
            options={
                'verbose_name': '문제: 템플릿 코드',
                'verbose_name_plural': '문제: 템플릿 코드',
                'db_table': 'problem_template',
                'ordering': ['problem', 'id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='languageinlecture',
            unique_together={('lecture', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='languageinproblem',
            unique_together={('problem', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='languageinchecker',
            unique_together={('checker', 'language')},
        ),
        migrations.CreateModel(
            name='StudentInLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', '학생'), ('professor', '교수'), ('admin', '관리자')], db_column='role', default='student', verbose_name='권한 및 역할')),
                ('student_code', models.CharField(db_column='StudentID', verbose_name='학번')),
                ('lecture', models.ForeignKey(db_column='lecture', on_delete=django.db.models.deletion.CASCADE, to='api.lecture', verbose_name='수업')),
                ('student', models.ForeignKey(db_column='student', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='학생')),
            ],
            options={
                'verbose_name': '수업: 참여학생',
                'verbose_name_plural': '수업: 참여학생',
                'db_table': 'STUDENT_IN_LECTURE',
                'ordering': ['lecture', 'student'],
                'unique_together': {('lecture', 'student')},
            },
        ),
    ]
