# Generated by Django 5.2.4 on 2025-08-03 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(db_column='BoardID', primary_key=True, serialize=False, verbose_name='게시판 고유 INDEX')),
                ('board_name', models.CharField(db_column='BoardName', max_length=100, verbose_name='게시판 이름')),
                ('description', models.TextField(blank=True, db_column='Description', null=True, verbose_name='게시판 설명')),
            ],
            options={
                'verbose_name': '게시판: 게시판',
                'verbose_name_plural': '게시판: 게시판',
                'db_table': 'board',
                'ordering': ['id', 'board_name'],
            },
        ),
        migrations.AlterField(
            model_name='languageinchecker',
            name='checker',
            field=models.ForeignKey(db_column='CheckerLang', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LanguageInChecker_checker', to='api.problemchecker', verbose_name='체커'),
        ),
        migrations.AlterField(
            model_name='languageinchecker',
            name='language',
            field=models.ForeignKey(db_column='CheckkerLang', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LanguageInChecker_language', to='api.language', verbose_name='언어'),
        ),
        migrations.AlterField(
            model_name='languageinlecture',
            name='language',
            field=models.ForeignKey(db_column='language', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LanguageInLecture_language', to='api.language', verbose_name='언어'),
        ),
        migrations.AlterField(
            model_name='languageinlecture',
            name='lecture',
            field=models.ForeignKey(db_column='lecture', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LanguageInLecture_lecture', to='api.lecture', verbose_name='수업'),
        ),
        migrations.AlterField(
            model_name='languageinproblem',
            name='language',
            field=models.ForeignKey(blank=True, db_column='LANG', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LanguageInProblem_language', to='api.language', verbose_name='언어'),
        ),
        migrations.AlterField(
            model_name='languageinproblem',
            name='problem',
            field=models.ForeignKey(db_column='PROB', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LanguageInProblem_problem', to='api.problem', verbose_name='문제'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='instructor',
            field=models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, related_name='Lecture_user', to=settings.AUTH_USER_MODEL, verbose_name='담당교수 고유 INDEX'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='maker',
            field=models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='Problem_user', to=settings.AUTH_USER_MODEL, verbose_name='출제자 유저 INDEX'),
        ),
        migrations.AlterField(
            model_name='problemchecker',
            name='problem',
            field=models.ForeignKey(db_column='ProblemID', on_delete=django.db.models.deletion.CASCADE, related_name='ProblemChecker_problem', to='api.problem', verbose_name='문제 고유 ID'),
        ),
        migrations.AlterField(
            model_name='probleminout',
            name='problem',
            field=models.ForeignKey(db_column='ProblemID', on_delete=django.db.models.deletion.CASCADE, related_name='ProblemInOut_problem', to='api.problem', verbose_name='문제 고유 INDEX'),
        ),
        migrations.AlterField(
            model_name='problemtemplate',
            name='problem',
            field=models.ForeignKey(db_column='ProblemID', on_delete=django.db.models.deletion.CASCADE, related_name='ProblemTemplate_problem', to='api.problem', verbose_name='문제 고유 INDEX'),
        ),
        migrations.AlterField(
            model_name='studentinlecture',
            name='lecture',
            field=models.ForeignKey(db_column='lecture', on_delete=django.db.models.deletion.CASCADE, related_name='StudentInLecture_lecture', to='api.lecture', verbose_name='수업'),
        ),
        migrations.AlterField(
            model_name='studentinlecture',
            name='student',
            field=models.ForeignKey(db_column='student', on_delete=django.db.models.deletion.CASCADE, related_name='StudentInLecture_user', to=settings.AUTH_USER_MODEL, verbose_name='학생'),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(db_column='ExamID', primary_key=True, serialize=False, verbose_name='시험 고유 INDEX')),
                ('exam_name', models.CharField(db_column='ExamName', max_length=255, verbose_name='시험 이름')),
                ('week', models.IntegerField(db_column='Week', verbose_name='시험 주차')),
                ('due_date', models.DateTimeField(db_column='DueDate', verbose_name='마감기한')),
                ('start_date', models.DateTimeField(db_column='StartDate', verbose_name='시작기간')),
                ('share', models.BooleanField(db_column='Share', default=False, verbose_name='공유여부')),
                ('lecture', models.ForeignKey(db_column='LectureID', on_delete=django.db.models.deletion.CASCADE, related_name='Exam_lecture', to='api.lecture', verbose_name='클래스 고유 INDEX')),
            ],
            options={
                'verbose_name': '시험: 시험',
                'verbose_name_plural': '시험: 시험',
                'db_table': 'exam',
                'ordering': ['id', 'exam_name', 'lecture'],
            },
        ),
        migrations.CreateModel(
            name='ExamProblem',
            fields=[
                ('id', models.BigAutoField(db_column='ExamProblemID', primary_key=True, serialize=False, verbose_name='시험문제 고유 INDEX')),
                ('score', models.IntegerField(blank=True, db_column='Score', null=True, verbose_name='점수')),
                ('exam', models.ForeignKey(db_column='ExamID', on_delete=django.db.models.deletion.CASCADE, related_name='ExamProblem_exam', to='api.exam', verbose_name='시험 고유 INDEX')),
                ('problem', models.ForeignKey(db_column='ProblemID', on_delete=django.db.models.deletion.CASCADE, related_name='ExamProblem_problem', to='api.problem', verbose_name='문제 고유 INDEX')),
            ],
            options={
                'verbose_name': '시험문제: 시험문제',
                'verbose_name_plural': '시험문제: 시험문제',
                'db_table': 'exam_problem',
                'ordering': ['id', 'exam'],
            },
        ),
        migrations.CreateModel(
            name='ExamSubmit',
            fields=[
                ('id', models.BigAutoField(db_column='SubmitID', primary_key=True, serialize=False, verbose_name='풀이 고유 INDEX')),
                ('code', models.TextField(db_column='Code', verbose_name='풀이코드')),
                ('score', models.IntegerField(db_column='Score', verbose_name='점수')),
                ('submission_time', models.DateTimeField(db_column='SubmissionTime', verbose_name='제출시간')),
                ('ip', models.CharField(db_column='IP', max_length=100, verbose_name='회원별 고유 IP')),
                ('execution_time', models.FloatField(db_column='ExecutionTime', verbose_name='실행시간')),
                ('error_message', models.TextField(blank=True, db_column='ErrorMessage', null=True, verbose_name='오류내용')),
                ('submission_count', models.IntegerField(db_column='SubmissionCount', verbose_name='제출 횟수')),
                ('judge_count', models.IntegerField(db_column='JudgeCount', verbose_name='채점 횟수')),
                ('status', models.TextField(db_column='Status', verbose_name='채점 상태')),
                ('memory', models.IntegerField(db_column='Memory', verbose_name='메모리')),
                ('exam', models.ForeignKey(db_column='ExamID', on_delete=django.db.models.deletion.CASCADE, related_name='ExamSubmit_exam', to='api.exam', verbose_name='시험 고유 INDEX')),
                ('problem', models.ForeignKey(db_column='ProblemID', on_delete=django.db.models.deletion.CASCADE, related_name='ExamSubmit_problem', to='api.examproblem', verbose_name='문제 고유 INDEX')),
                ('user', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, related_name='ExamSubmit_user', to=settings.AUTH_USER_MODEL, verbose_name='유저 INDEX')),
            ],
            options={
                'verbose_name': '시험풀이: 시험풀이',
                'verbose_name_plural': '시험풀이: 시험풀이',
                'db_table': 'exam_submit',
                'ordering': ['id', 'exam', 'problem'],
            },
        ),
        migrations.CreateModel(
            name='ExamUser',
            fields=[
                ('id', models.BigAutoField(db_column='ExamUserID', primary_key=True, serialize=False, verbose_name='시험인원 고유 INDEX')),
                ('start_time', models.DateTimeField(db_column='StartTime', verbose_name='시험시작 시간')),
                ('end_time', models.DateTimeField(db_column='EndTime', verbose_name='시험종료 시간')),
                ('saved_code', models.TextField(blank=True, db_column='SavedCode', null=True, verbose_name='중간 저장 코드')),
                ('exam', models.ForeignKey(db_column='ExamID', on_delete=django.db.models.deletion.CASCADE, related_name='ExamUser_exam', to='api.exam', verbose_name='시험 고유 INDEX')),
                ('lecture_user', models.ForeignKey(db_column='LectureUserID', on_delete=django.db.models.deletion.CASCADE, related_name='ExamUser_StudentInLecture', to='api.studentinlecture', verbose_name='클래스 인원 고유 INDEX')),
            ],
            options={
                'verbose_name': '시험인원: 시험인원',
                'verbose_name_plural': '시험인원: 시험인원',
                'db_table': 'exam_user',
                'ordering': ['id', 'exam'],
            },
        ),
        migrations.CreateModel(
            name='LanguageInExamSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_submit', models.ForeignKey(blank=True, db_column='EXAM-SUB', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LanguageInExamSubmit_examsubmit', to='api.examsubmit', verbose_name='시험풀이')),
                ('language', models.ForeignKey(blank=True, db_column='LANG', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LanguageInExamSubmit_language', to='api.language', verbose_name='언어')),
            ],
            options={
                'verbose_name': '시험풀이: 사용언어',
                'verbose_name_plural': '시험풀이: 사용언어',
                'db_table': 'LANGUAGE_IN_EXAMSUBMIT',
                'ordering': ['exam_submit', 'language'],
                'unique_together': {('exam_submit', 'language')},
            },
        ),
        migrations.AddField(
            model_name='examsubmit',
            name='language',
            field=models.ManyToManyField(blank=True, db_column='ExamSubmitLanguage', through='api.LanguageInExamSubmit', through_fields=('exam_submit', 'language'), to='api.language', verbose_name='풀이언어'),
        ),
        migrations.CreateModel(
            name='LanguageInProblemSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(db_column='LANG', on_delete=django.db.models.deletion.CASCADE, related_name='LanguageInProblemSubmit_language', to='api.language', verbose_name='언어')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(db_column='PostID', primary_key=True, serialize=False, verbose_name='게시글 고유 INDEX')),
                ('title', models.CharField(db_column='Title', max_length=255, verbose_name='게시글 제목')),
                ('content', models.TextField(db_column='Content', verbose_name='게시글 내용')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='created_date', verbose_name='업로드 날짜')),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='updated_date', verbose_name='수정 날짜')),
                ('board', models.ForeignKey(db_column='BoardID', on_delete=django.db.models.deletion.CASCADE, related_name='post_board', to='api.board', verbose_name='게시판 고유 INDEX')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to=settings.AUTH_USER_MODEL, verbose_name='작성 유저 INDEX')),
            ],
            options={
                'verbose_name': '게시글: 게시글',
                'verbose_name_plural': '게시글: 게시글',
                'db_table': 'post',
                'ordering': ['-created_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PostLecture',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='분반별 게시글 고유 INDEX')),
                ('is_noticed', models.BooleanField(db_column='isNoticed', default=False, verbose_name='공지사항 여부')),
                ('class_id', models.ForeignKey(db_column='ClassID', on_delete=django.db.models.deletion.CASCADE, related_name='PostLecture_lecture', to='api.lecture', verbose_name='클래스 고유 INDEX')),
                ('post', models.ForeignKey(db_column='PostID', on_delete=django.db.models.deletion.CASCADE, related_name='PostLecture_post', to='api.post', verbose_name='게시글 고유 INDEX')),
            ],
            options={
                'verbose_name': '분반별 게시글: 분반별 게시글',
                'verbose_name_plural': '분반별 게시글: 분반별 게시글',
                'db_table': 'post_lecture',
                'ordering': ['id', 'is_noticed', 'post'],
            },
        ),
        migrations.CreateModel(
            name='PostReply',
            fields=[
                ('id', models.BigAutoField(db_column='ReplayId', primary_key=True, serialize=False, verbose_name='답변 고유 INDEX')),
                ('reply_content', models.TextField(db_column='ReplyContent', verbose_name='답변 내용')),
                ('reply_date', models.DateTimeField(auto_now_add=True, db_column='ReplyDate', verbose_name='답변 날짜')),
                ('board', models.ForeignKey(db_column='BoardID', on_delete=django.db.models.deletion.CASCADE, related_name='PostReply_board', to='api.board', verbose_name='게시판 고유 INDEX')),
                ('post', models.ForeignKey(db_column='PostID', on_delete=django.db.models.deletion.CASCADE, related_name='PostReply_post', to='api.post', verbose_name='질문글 고유 INDEX')),
                ('user', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, related_name='PostReply_user', to=settings.AUTH_USER_MODEL, verbose_name='답변유저 INDEX')),
            ],
            options={
                'verbose_name': '게시판답변: 게시판답변',
                'verbose_name_plural': '게시판답변: 게시판답변',
                'db_table': 'post_reply',
                'ordering': ['-reply_date'],
            },
        ),
        migrations.CreateModel(
            name='ProblemPost',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='질문게시글 고유 INDEX')),
                ('post', models.ForeignKey(db_column='PostID', on_delete=django.db.models.deletion.CASCADE, related_name='ProblemPost_post', to='api.post', verbose_name='게시글')),
                ('problem', models.ForeignKey(db_column='ProblemID', on_delete=django.db.models.deletion.CASCADE, related_name='ProblemPost_problem', to='api.problem', verbose_name='문제')),
            ],
            options={
                'verbose_name': '질문게시글: 질문게시글',
                'verbose_name_plural': '질문게시글: 질문게시글',
                'db_table': 'problem_post',
                'ordering': ['id', 'post', 'problem'],
            },
        ),
        migrations.CreateModel(
            name='ProblemSubmit',
            fields=[
                ('id', models.BigAutoField(db_column='SolveID', primary_key=True, serialize=False, verbose_name='풀이 고유 INDEX')),
                ('code', models.TextField(db_column='Code', verbose_name='풀이코드')),
                ('score', models.IntegerField(db_column='Score', verbose_name='점수')),
                ('submission_time', models.DateTimeField(db_column='SubmissionTime', verbose_name='제출시간')),
                ('execution_time', models.FloatField(db_column='ExecutionTime', verbose_name='실행시간')),
                ('error_message', models.TextField(blank=True, db_column='ErrorMessage', null=True, verbose_name='오류내용')),
                ('submission_count', models.IntegerField(db_column='SubmissionCount', verbose_name='제출횟수')),
                ('judge_count', models.IntegerField(db_column='JudgeCount', verbose_name='채점횟수')),
                ('status', models.TextField(db_column='Status', verbose_name='채점상태')),
                ('memory', models.IntegerField(db_column='Memory', verbose_name='메모리')),
                ('language', models.ManyToManyField(blank=True, through='api.LanguageInProblemSubmit', through_fields=('problem_submit', 'language'), to='api.language', verbose_name='풀이언어')),
                ('user', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, related_name='ProblemSubmit_submit', to=settings.AUTH_USER_MODEL, verbose_name='유저 INDEX')),
            ],
            options={
                'verbose_name': '과제풀이: 과제풀이',
                'verbose_name_plural': '과제풀이: 과제풀이',
                'db_table': 'problem_submit',
                'ordering': ['id', 'user'],
            },
        ),
        migrations.AddField(
            model_name='languageinproblemsubmit',
            name='problem_submit',
            field=models.ForeignKey(db_column='PROB_SUBMIT', on_delete=django.db.models.deletion.CASCADE, related_name='LanguageInProblemSubmit_problemsubmit', to='api.problemsubmit', verbose_name='과제풀이'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(db_column='SectionID', primary_key=True, serialize=False, verbose_name='섹션 고유 INDEX')),
                ('section_name', models.CharField(db_column='SectionName', max_length=100, verbose_name='과제 이름')),
                ('week', models.IntegerField(db_column='Week', verbose_name='과제주차')),
                ('share', models.BooleanField(db_column='Share', default=False, verbose_name='공유 여부')),
                ('lecture', models.ForeignKey(db_column='LectureID', on_delete=django.db.models.deletion.CASCADE, related_name='Section_lecture', to='api.lecture', verbose_name='클래스 고유 INDEX')),
            ],
            options={
                'verbose_name': '강의: 섹션',
                'verbose_name_plural': '강의: 섹션',
                'db_table': 'section',
                'ordering': ['id', 'section_name'],
            },
        ),
        migrations.AddField(
            model_name='problemsubmit',
            name='section',
            field=models.ForeignKey(db_column='SectionID', on_delete=django.db.models.deletion.CASCADE, related_name='ProblemSubmit_section', to='api.section', verbose_name='섹션 고유 INDEX'),
        ),
        migrations.CreateModel(
            name='SectionProblem',
            fields=[
                ('id', models.BigAutoField(db_column='SectionProblemID', primary_key=True, serialize=False, verbose_name='과제문제 고유 INDEX')),
                ('start_date', models.DateTimeField(db_column='StartDate', verbose_name='시작기간')),
                ('due_date', models.DateTimeField(db_column='DueDate', verbose_name='마감기한')),
                ('problem', models.ForeignKey(db_column='ProblemID', on_delete=django.db.models.deletion.CASCADE, related_name='SectionProblem_problem', to='api.problem', verbose_name='문제 고유 INDEX')),
                ('section', models.ForeignKey(db_column='SectionID', on_delete=django.db.models.deletion.CASCADE, related_name='SectionProblem_section', to='api.section', verbose_name='섹션 고유 INDEX')),
            ],
            options={
                'verbose_name': '과제문제: 과제문제',
                'verbose_name_plural': '과제문제: 과제문제',
                'db_table': 'section_problem',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='problemsubmit',
            name='section_problem',
            field=models.ForeignKey(db_column='SectionProblemID', on_delete=django.db.models.deletion.CASCADE, related_name='ProblemSubmit_sectionproblem', to='api.sectionproblem', verbose_name='과제문제 고유 INDEX'),
        ),
    ]
