# Generated by Django 5.2.4 on 2025-08-07 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_board_alter_languageinchecker_checker_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postreply',
            options={'ordering': ['-reply_date'], 'verbose_name': '게시글답변: 게시글답변', 'verbose_name_plural': '게시글답글: 게시글답변'},
        ),
        migrations.AddField(
            model_name='problemtemplate',
            name='language',
            field=models.ForeignKey(db_column='languageID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ProblemTemplate_language', to='api.language', verbose_name='언어 INDEX'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_language',
            field=models.ManyToManyField(blank=True, related_name='lecture_language_language', through='api.LanguageInLecture', through_fields=('lecture', 'language'), to='api.language', verbose_name='클래스 기본 언어'),
        ),
    ]
