# Generated by Django 5.2.4 on 2025-08-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_postreply_options_problemtemplate_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemtemplate',
            name='language',
        ),
    ]
