# Generated by Django 5.2.4 on 2025-08-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_problemtemplate_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examsubmit',
            options={'ordering': ['id'], 'verbose_name': '시험풀이: 시험풀이', 'verbose_name_plural': '시험풀이: 시험풀이'},
        ),
        migrations.AlterModelOptions(
            name='languageinexamsubmit',
            options={'ordering': ['id'], 'verbose_name': '시험풀이: 사용언어', 'verbose_name_plural': '시험풀이: 사용언어'},
        ),
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, db_column='Description', null=True, verbose_name='시험 설명'),
        ),
    ]
