# Generated by Django 5.2.4 on 2025-08-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_examsubmit_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="description",
            field=models.TextField(
                blank=True, db_column="Description", null=True, verbose_name="과제 설명"
            ),
        ),
        migrations.AlterField(
            model_name="studentinlecture",
            name="role",
            field=models.CharField(
                choices=[("student", "학생"), ("professor", "교수"), ("admin", "관리자")],
                db_column="role",
                default="student",
                max_length=50,
                verbose_name="권한 및 역할",
            ),
        ),
        migrations.AlterField(
            model_name="studentinlecture",
            name="student_code",
            field=models.CharField(
                db_column="StudentID", max_length=50, verbose_name="학번"
            ),
        ),
    ]
