# Generated by Django 5.2.4 on 2025-09-02 04:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ("api", "0006_section_description_alter_studentinlecture_role_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LanguageInSectionProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "과제문제: 사용언어",
                "verbose_name_plural": "과제문제: 사용언어",
                "db_table": "LANGUAGE_IN_SECTIONPROBLEM",
                "ordering": ["section_problem", "language"],
            },
        ),
        migrations.AlterModelOptions(
            name="languageinlecture",
            options={
                "ordering": ["lecture", "language"],
                "verbose_name": "수업: 사용언어",
                "verbose_name_plural": "수업: 사용언어",
            },
        ),
        migrations.AddField(
            model_name="languageinsectionproblem",
            name="language",
            field=models.ForeignKey(
                db_column="language",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="LanguageInSection_language",
                to="api.language",
                verbose_name="언어",
            ),
        ),
        migrations.AddField(
            model_name="languageinsectionproblem",
            name="section_problem",
            field=models.ForeignKey(
                db_column="sectionProblem",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="LanguageInSectionProblem_sectionProblem",
                to="api.sectionproblem",
                verbose_name="과제 문제",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="languageinsectionproblem",
            unique_together={("section_problem", "language")},
        ),
    ]
