# Generated by Django 5.2.4 on 2025-09-05 05:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_languageinsectionproblem_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="languageinproblemsubmit",
            options={
                "ordering": ["id"],
                "verbose_name": "과제풀이: 사용언어",
                "verbose_name_plural": "과제풀이: 사용언어",
            },
        ),
        migrations.AlterModelOptions(
            name="languageinsectionproblem",
            options={"ordering": ["section_problem", "language"]},
        ),
        migrations.AlterModelOptions(
            name="postreply",
            options={
                "ordering": ["-reply_date"],
                "verbose_name": "게시글답변: 게시글답변",
                "verbose_name_plural": "게시글답변: 게시글답변",
            },
        ),
        migrations.AddField(
            model_name="problem",
            name="pdf_path",
            field=models.TextField(
                blank=True, db_column="PdfFilePath", null=True, verbose_name="pdf파일"
            ),
        ),
        migrations.AddField(
            model_name="sectionproblem",
            name="language",
            field=models.ManyToManyField(
                blank=True,
                related_name="section_problems",
                through="api.LanguageInSectionProblem",
                to="api.language",
            ),
        ),
        migrations.AddField(
            model_name="studentinlecture",
            name="is_delete",
            field=models.BooleanField(
                db_column="isDeleted", default=False, verbose_name="삭제여부"
            ),
        ),
        migrations.AlterField(
            model_name="languageinsectionproblem",
            name="language",
            field=models.ForeignKey(
                db_column="language",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="language_links",
                to="api.language",
                verbose_name="언어",
            ),
        ),
        migrations.AlterField(
            model_name="languageinsectionproblem",
            name="section_problem",
            field=models.ForeignKey(
                db_column="sectionProblem",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="language_links",
                to="api.sectionproblem",
                verbose_name="과제 문제",
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="limit_memory",
            field=models.PositiveIntegerField(
                db_column="LimitMemory",
                help_text="메가바이트 단위",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="제한메모리(MB)",
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="limit_time",
            field=models.PositiveIntegerField(
                db_column="LimitTime",
                help_text="밀리초 단위",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="제한시간(ms)",
            ),
        ),
        migrations.AlterField(
            model_name="problemchecker",
            name="checker_language",
            field=models.ManyToManyField(
                blank=True,
                related_name="checker_language",
                through="api.LanguageInChecker",
                through_fields=("checker", "language"),
                to="api.language",
                verbose_name="체커 사용 언어",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="languageinproblemsubmit",
            unique_together={("problem_submit", "language")},
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["lecture", "week"], name="section_Lecture_8798a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(fields=["share"], name="section_Share_d2926c_idx"),
        ),
        migrations.AddIndex(
            model_name="sectionproblem",
            index=models.Index(
                fields=["section", "-start_date"], name="section_pro_Section_974622_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sectionproblem",
            index=models.Index(
                fields=["problem"], name="section_pro_Problem_bbbac0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sectionproblem",
            index=models.Index(
                fields=["start_date", "due_date"], name="section_pro_StartDa_210914_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.CheckConstraint(
                condition=models.Q(("week__gte", 1)), name="section_week_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                fields=("lecture", "section_name"), name="uniq_section_per_lecture"
            ),
        ),
        migrations.AddConstraint(
            model_name="sectionproblem",
            constraint=models.CheckConstraint(
                condition=models.Q(("due_date__gt", models.F("start_date"))),
                name="sectionproblem_due_gt_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="sectionproblem",
            constraint=models.UniqueConstraint(
                fields=("section", "problem", "start_date", "due_date"),
                name="uniq_section_problem_window",
            ),
        ),
        migrations.AlterModelTable(
            name="languageinproblemsubmit",
            table="LANGUAGE_IN_PROBLEMSUBMIT",
        ),
    ]
