# Generated by Django 5.2.4 on 2025-09-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_languageinproblemsubmit_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='pdf_path',
        ),
        migrations.AlterField(
            model_name='problem',
            name='limit_memory',
            field=models.PositiveIntegerField(db_column='LimitMemory', help_text='메가바이트 단위', verbose_name='제한메모리(MB)'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='limit_time',
            field=models.PositiveIntegerField(db_column='LimitTime', help_text='밀리초 단위', verbose_name='제한시간(ms)'),
        ),
    ]
