# Generated by Django 5.2.4 on 2025-09-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_problem_pdf_path_alter_problem_limit_memory_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="problem",
            old_name="level",
            new_name="difficulty",
        ),
    ]
