# Generated by Django 5.2.4 on 2025-09-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_rename_level_problem_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionproblem",
            name="is_delete",
            field=models.BooleanField(
                db_column="isDeleted", default=False, verbose_name="삭제여부"
            ),
        ),
    ]
