# Generated by Django 5.2.4 on 2025-10-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_sectionproblem_is_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="is_delete",
            field=models.BooleanField(
                db_column="isDeleted", default=False, verbose_name="삭제여부"
            ),
        ),
    ]
