# Generated by Django 5.2.4 on 2025-11-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_section_is_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_delete",
            field=models.BooleanField(
                db_column="isDeleted", default=False, verbose_name="삭제여부"
            ),
        ),
        migrations.AddField(
            model_name="postreply",
            name="is_delete",
            field=models.BooleanField(
                db_column="isDeleted", default=False, verbose_name="삭제 여부"
            ),
        ),
    ]
