# Generated by Django 5.2.4 on 2025-11-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_section_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='content_path',
        ),
        migrations.AddField(
            model_name='problem',
            name='share',
            field=models.BooleanField(db_column='Share', default=False, verbose_name='공유여부'),
        ),
        migrations.AlterField(
            model_name='examsubmit',
            name='execution_time',
            field=models.FloatField(blank=True, db_column='ExecutionTime', null=True, verbose_name='실행시간'),
        ),
        migrations.AlterField(
            model_name='examsubmit',
            name='memory',
            field=models.IntegerField(blank=True, db_column='Memory', null=True, verbose_name='메모리'),
        ),
        migrations.AlterField(
            model_name='examsubmit',
            name='score',
            field=models.IntegerField(blank=True, db_column='Score', null=True, verbose_name='점수'),
        ),
        migrations.AlterField(
            model_name='problemsubmit',
            name='execution_time',
            field=models.FloatField(blank=True, db_column='ExecutionTime', null=True, verbose_name='실행시간'),
        ),
        migrations.AlterField(
            model_name='problemsubmit',
            name='memory',
            field=models.IntegerField(blank=True, db_column='Memory', null=True, verbose_name='메모리'),
        ),
        migrations.AlterField(
            model_name='problemsubmit',
            name='score',
            field=models.IntegerField(blank=True, db_column='Score', null=True, verbose_name='점수'),
        ),
    ]
