# Generated by Django 5.2.4 on 2025-11-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_sectionproblem_score_alter_examsubmit_execution_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionproblem',
            name='score',
            field=models.IntegerField(blank=True, db_column='Score', null=True, verbose_name='점수'),
        ),
    ]
