# Generated by Django 5.2.4 on 2025-11-17 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_post_is_delete_postreply_is_delete_and_more'),
        ('api', '0013_remove_problem_content_path_problem_share_and_more'),
        ('api', '0014_alter_sectionproblem_score'),
    ]

    operations = [
    ]
