# Generated by Django 5.2.4 on 2025-12-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_merge_20251117_1524"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="postlecture",
            constraint=models.UniqueConstraint(
                fields=("post", "class_id"), name="unique_post_class"
            ),
        ),
        migrations.AddConstraint(
            model_name="problempost",
            constraint=models.UniqueConstraint(
                fields=("post", "problem"), name="unique_post_problem"
            ),
        ),
    ]
