# Generated by Django 5.2.4 on 2025-12-26 07:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_uuid_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='게시판 UUID'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='시험 UUID'),
        ),
        migrations.AlterField(
            model_name='examproblem',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='시험문제 UUID'),
        ),
        migrations.AlterField(
            model_name='examsubmit',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='시험 풀이 UUID'),
        ),
        migrations.AlterField(
            model_name='examuser',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='시험인원 UUID'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='클래스 UUID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='게시글 UUID'),
        ),
        migrations.AlterField(
            model_name='postlecture',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='분반별 게시글 UUID'),
        ),
        migrations.AlterField(
            model_name='postreply',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='답변 UUID'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='문제 UUID'),
        ),
        migrations.AlterField(
            model_name='problemchecker',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='체커코드 UUID'),
        ),
        migrations.AlterField(
            model_name='probleminout',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='입출력 UUID'),
        ),
        migrations.AlterField(
            model_name='problempost',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='질문게시글 UUID'),
        ),
        migrations.AlterField(
            model_name='problemsubmit',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='풀이 UUID'),
        ),
        migrations.AlterField(
            model_name='problemtemplate',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='샘플코드 UUID'),
        ),
        migrations.AlterField(
            model_name='section',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='섹션 UUID'),
        ),
        migrations.AlterField(
            model_name='sectionproblem',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='과제문제 UUID'),
        ),
        migrations.AlterField(
            model_name='studentinlecture',
            name='student',
            field=models.ForeignKey(blank=True, db_column='student', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='StudentInLecture_user', to=settings.AUTH_USER_MODEL, verbose_name='학생'),
        ),
        migrations.AlterField(
            model_name='studentinlecture',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='수업참여 UUID'),
        ),
    ]
