# Generated by Codex on 2026-01-21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_postlecture_unique_post_class_and_more"),
        ("api", "0017_alter_board_uuid_alter_exam_uuid_and_more"),
        ("api", "0018_add_like_view_counts_to_submissions"),
    ]

    operations = []
