# Generated by Django 5.2.4 on 2026-02-04 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_merge_20260121_1915'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='examuser',
            name='lecture_user',
            field=models.ForeignKey(blank=True, db_column='LectureUserID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ExamUser_StudentInLecture', to='api.studentinlecture', verbose_name='클래스 인원 고유 INDEX'),
        ),
        migrations.AddIndex(
            model_name='examsubmit',
            index=models.Index(fields=['user', 'exam', 'problem'], name='es_user_exam_pb_idx'),
        ),
        migrations.AddIndex(
            model_name='examsubmit',
            index=models.Index(fields=['problem', 'user', 'exam'], name='es_pb_user_exam_idx'),
        ),
        migrations.AddIndex(
            model_name='examsubmit',
            index=models.Index(fields=['problem', 'user', '-submission_time', '-id'], name='es_pb_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['instructor', 'is_delete'], name='lecture_inst_del_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_delete', 'id'], name='post_del_id_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['board', 'is_delete', '-created_date'], name='post_board_del_ct_idx'),
        ),
        migrations.AddIndex(
            model_name='postlecture',
            index=models.Index(fields=['class_id', 'is_noticed', 'post'], name='pl_class_notice_p_idx'),
        ),
        migrations.AddIndex(
            model_name='postreply',
            index=models.Index(fields=['post', 'is_delete', '-reply_date'], name='pr_post_del_rd_idx'),
        ),
        migrations.AddIndex(
            model_name='problemsubmit',
            index=models.Index(fields=['user', 'section', 'section_problem'], name='ps_user_sec_sp_idx'),
        ),
        migrations.AddIndex(
            model_name='problemsubmit',
            index=models.Index(fields=['section_problem', 'user'], name='ps_sp_user_idx'),
        ),
        migrations.AddIndex(
            model_name='problemsubmit',
            index=models.Index(fields=['section_problem', 'user', '-submission_time', '-id'], name='ps_sp_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='studentinlecture',
            index=models.Index(fields=['lecture', 'is_delete'], name='sil_lecture_del_idx'),
        ),
        migrations.AddIndex(
            model_name='studentinlecture',
            index=models.Index(fields=['lecture', 'student_code'], name='sil_lecture_code_idx'),
        ),
    ]
