# Generated by Codex on 2026-02-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_merge_20260208_0000"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="is_delete",
            field=models.BooleanField(
                db_column="isDeleted", default=False, verbose_name="삭제여부"
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="is_delete",
            field=models.BooleanField(
                db_column="isDeleted", default=False, verbose_name="삭제여부"
            ),
        ),
        migrations.AddField(
            model_name="problemtemplate",
            name="is_delete",
            field=models.BooleanField(
                db_column="isDeleted", default=False, verbose_name="삭제여부"
            ),
        ),
        migrations.AddField(
            model_name="probleminout",
            name="is_delete",
            field=models.BooleanField(
                db_column="isDeleted", default=False, verbose_name="삭제여부"
            ),
        ),
        migrations.AddField(
            model_name="problemchecker",
            name="is_delete",
            field=models.BooleanField(
                db_column="isDeleted", default=False, verbose_name="삭제여부"
            ),
        ),
        migrations.AddField(
            model_name="languageinchecker",
            name="is_delete",
            field=models.BooleanField(
                db_column="isDeleted", default=False, verbose_name="삭제여부"
            ),
        ),
        migrations.AddField(
            model_name="languageinproblem",
            name="is_delete",
            field=models.BooleanField(
                db_column="isDeleted", default=False, verbose_name="삭제여부"
            ),
        ),
        migrations.AddField(
            model_name="languageinlecture",
            name="is_delete",
            field=models.BooleanField(
                db_column="isDeleted", default=False, verbose_name="삭제여부"
            ),
        ),
        migrations.AddField(
            model_name="languageinsectionproblem",
            name="is_delete",
            field=models.BooleanField(
                db_column="isDeleted", default=False, verbose_name="삭제여부"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="is_delete",
            field=models.BooleanField(
                db_column="isDeleted", default=False, verbose_name="삭제여부"
            ),
        ),
        migrations.AddField(
            model_name="examuser",
            name="is_delete",
            field=models.BooleanField(
                db_column="isDeleted", default=False, verbose_name="삭제여부"
            ),
        ),
        migrations.AddField(
            model_name="examproblem",
            name="is_delete",
            field=models.BooleanField(
                db_column="isDeleted", default=False, verbose_name="삭제여부"
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="is_delete",
            field=models.BooleanField(
                db_column="isDeleted", default=False, verbose_name="삭제여부"
            ),
        ),
        migrations.AddField(
            model_name="problempost",
            name="is_delete",
            field=models.BooleanField(
                db_column="isDeleted", default=False, verbose_name="삭제여부"
            ),
        ),
        migrations.AddField(
            model_name="postlecture",
            name="is_delete",
            field=models.BooleanField(
                db_column="isDeleted", default=False, verbose_name="삭제여부"
            ),
        ),
        migrations.AddField(
            model_name="problemsubmit",
            name="is_delete",
            field=models.BooleanField(
                db_column="isDeleted", default=False, verbose_name="삭제여부"
            ),
        ),
        migrations.AddField(
            model_name="languageinproblemsubmit",
            name="is_delete",
            field=models.BooleanField(
                db_column="isDeleted", default=False, verbose_name="삭제여부"
            ),
        ),
        migrations.AddField(
            model_name="examsubmit",
            name="is_delete",
            field=models.BooleanField(
                db_column="isDeleted", default=False, verbose_name="삭제여부"
            ),
        ),
        migrations.AddField(
            model_name="languageinexamsubmit",
            name="is_delete",
            field=models.BooleanField(
                db_column="isDeleted", default=False, verbose_name="삭제여부"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="languageinchecker",
            unique_together={("checker", "language", "is_delete")},
        ),
        migrations.AlterUniqueTogether(
            name="languageinproblem",
            unique_together={("problem", "language", "is_delete")},
        ),
        migrations.AlterUniqueTogether(
            name="languageinlecture",
            unique_together={("lecture", "language", "is_delete")},
        ),
        migrations.AlterUniqueTogether(
            name="languageinsectionproblem",
            unique_together={("section_problem", "language", "is_delete")},
        ),
        migrations.AlterUniqueTogether(
            name="languageinproblemsubmit",
            unique_together={("problem_submit", "language", "is_delete")},
        ),
        migrations.AlterUniqueTogether(
            name="languageinexamsubmit",
            unique_together={("exam_submit", "language", "is_delete")},
        ),
        migrations.RemoveConstraint(
            model_name="section",
            name="uniq_section_per_lecture",
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                fields=("lecture", "section_name", "is_delete"),
                name="uniq_section_per_lecture",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="sectionproblem",
            name="uniq_section_problem_window",
        ),
        migrations.AddConstraint(
            model_name="sectionproblem",
            constraint=models.UniqueConstraint(
                fields=("section", "problem", "start_date", "due_date", "is_delete"),
                name="uniq_section_problem_window",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="problempost",
            name="unique_post_problem",
        ),
        migrations.AddConstraint(
            model_name="problempost",
            constraint=models.UniqueConstraint(
                fields=("post", "problem", "is_delete"),
                name="unique_post_problem",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="postlecture",
            name="unique_post_class",
        ),
        migrations.AddConstraint(
            model_name="postlecture",
            constraint=models.UniqueConstraint(
                fields=("post", "class_id", "is_delete"),
                name="unique_post_class",
            ),
        ),
    ]
