# Generated by Django 5.2.4 on 2026-02-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_soft_delete_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreply',
            name='is_delete',
            field=models.BooleanField(db_column='isDeleted', default=False, verbose_name='삭제여부'),
        ),
    ]
