# Generated by ChatGPT on 2026-02-12
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_dedupe_examuser_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_noticed",
            field=models.BooleanField(
                db_column="isNoticed",
                default=False,
                verbose_name="공지사항 여부",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["board", "is_delete", "is_noticed", "-created_date"],
                name="post_board_notice_ct_idx",
            ),
        ),
    ]
