# Generated by Django 5.2.4 on 2026-02-27 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_add_problem_search_trigram_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-is_noticed', '-created_date', 'title'], 'verbose_name': '게시글: 게시글', 'verbose_name_plural': '게시글: 게시글'},
        ),
    ]
