# Generated by Django 5.2.4 on 2026-03-29 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_alter_post_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="postreply",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_column="ParentReplyId",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="api.postreply",
                verbose_name="부모 답변 INDEX",
            ),
        ),
    ]
