"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from dotenv import load_dotenv
from . import BASE_DIR
from django.core.exceptions import ImproperlyConfigured


load_dotenv(os.path.join(BASE_DIR, ".env"))


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "t", "yes", "y", "on"}


def _env_list(name: str, default: list[str]) -> list[str]:
    raw = os.getenv(name)
    if not raw:
        return default
    return [item.strip() for item in raw.split(",") if item.strip()]


def _build_redis_url(host: str, port: int | str, db: int | str, password: str | None = None) -> str:
    password = (password or "").strip()
    auth = f":{password}@" if password else ""
    return f"redis://{auth}{host}:{port}/{db}"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

DEBUG = _env_bool("DEBUG", default=False)
if not SECRET_KEY:
    raise ImproperlyConfigured("SECRET_KEY environment variable is required.")
if not DEBUG and SECRET_KEY.startswith("django-insecure-"):
    raise ImproperlyConfigured(
        "Insecure default SECRET_KEY is not allowed when DEBUG=False."
    )

_default_allowed_hosts = ["example.com"]
if DEBUG:
    _default_allowed_hosts.extend(["localhost", "127.0.0.1", "backend"])

ALLOWED_HOSTS = _env_list("ALLOWED_HOSTS", _default_allowed_hosts)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DB_HOST = os.environ.get('DB_HOST')
DB_PORT = os.environ.get('DB_PORT', '5432')
DB_USE_PGBOUNCER = _env_bool(
    'DB_USE_PGBOUNCER',
    default=(DB_HOST or '').strip().lower() == 'pgbouncer',
)
DB_CONN_MAX_AGE = int(os.environ.get('DB_CONN_MAX_AGE', '0' if DB_USE_PGBOUNCER else '60'))
DB_DISABLE_SERVER_SIDE_CURSORS = _env_bool(
    'DB_DISABLE_SERVER_SIDE_CURSORS',
    default=DB_USE_PGBOUNCER,
)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': DB_HOST,
        'PORT': DB_PORT,
        'CONN_MAX_AGE': DB_CONN_MAX_AGE,
        'DISABLE_SERVER_SIDE_CURSORS': DB_DISABLE_SERVER_SIDE_CURSORS,
    }
}

# CSRF
_default_csrf_trusted_origins = ["https://example.com"]
if DEBUG:
    _default_csrf_trusted_origins.extend(
        [
            "http://localhost:3000",
            "http://127.0.0.1:3000",
            "http://localhost:8000",
            "http://127.0.0.1:8000",
        ]
    )

CSRF_TRUSTED_ORIGINS = _env_list("CSRF_TRUSTED_ORIGINS", _default_csrf_trusted_origins)

REDIS_PASSWORD = (os.getenv("REDIS_PASSWORD") or "").strip() or None
REDIS_HOST = os.getenv("REDIS_HOST", "redis-cache")
REDIS_PORT = int(os.getenv("REDIS_PORT", "6379"))
REDIS_DB = int(os.getenv("REDIS_DB", "0"))
REDIS_SOCKET_CONNECT_TIMEOUT = float(os.getenv("REDIS_SOCKET_CONNECT_TIMEOUT", "1.0"))
REDIS_SOCKET_TIMEOUT = float(os.getenv("REDIS_SOCKET_TIMEOUT", "1.0"))
REDIS_FAILURE_COOLDOWN_SECONDS = float(os.getenv("REDIS_FAILURE_COOLDOWN_SECONDS", "30"))
REDIS_URL = os.getenv("REDIS_URL") or _build_redis_url(
    REDIS_HOST,
    REDIS_PORT,
    REDIS_DB,
    REDIS_PASSWORD,
)

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL,
        "KEY_PREFIX": "algolab",
        "TIMEOUT": 300,
        "OPTIONS": {
            "socket_connect_timeout": REDIS_SOCKET_CONNECT_TIMEOUT,
            "socket_timeout": REDIS_SOCKET_TIMEOUT,
        },
    }
}

RQ_QUEUES = {
    "default": {"URL": REDIS_URL, "DEFAULT_TIMEOUT": 600},
    "execution": {"URL": REDIS_URL, "DEFAULT_TIMEOUT": 120},
    "grading": {"URL": REDIS_URL, "DEFAULT_TIMEOUT": 1200},
}

# Grade result Redis (채점 컨테이너가 결과를 넣어두는 곳)
GRADE_RESULT_REDIS_HOST = os.getenv("GRADE_RESULT_REDIS_HOST", "redis-result")
GRADE_RESULT_REDIS_PORT = int(os.getenv("GRADE_RESULT_REDIS_PORT", "6379"))
GRADE_RESULT_REDIS_DB = int(os.getenv("GRADE_RESULT_REDIS_DB", "0"))
GRADE_RESULT_REDIS_URL = os.getenv("GRADE_RESULT_REDIS_URL") or _build_redis_url(
    GRADE_RESULT_REDIS_HOST,
    GRADE_RESULT_REDIS_PORT,
    GRADE_RESULT_REDIS_DB,
    REDIS_PASSWORD,
)

API_QUERY_METRICS_ENABLED = os.getenv("API_QUERY_METRICS_ENABLED", "0") == "1"
API_QUERY_METRICS_SLOW_MS = int(os.getenv("API_QUERY_METRICS_SLOW_MS", "500"))
API_QUERY_METRICS_LOG_SQL = os.getenv("API_QUERY_METRICS_LOG_SQL", "0") == "1"
API_QUERY_METRICS_MAX_SQL = int(os.getenv("API_QUERY_METRICS_MAX_SQL", "5"))
API_CACHE_ENABLED = os.getenv("API_CACHE_ENABLED", "1") == "1"
API_CACHE_BOARD_LIST_TTL = int(os.getenv("API_CACHE_BOARD_LIST_TTL", "20"))
API_CACHE_BOARD_DETAIL_TTL = int(os.getenv("API_CACHE_BOARD_DETAIL_TTL", "20"))
API_CACHE_LIST_TTL = int(os.getenv("API_CACHE_LIST_TTL", "30"))
OAUTH_TOKEN_CACHE_TTL = int(os.getenv("OAUTH_TOKEN_CACHE_TTL", "900"))
OAUTH_TOKEN_TIMEOUT = float(os.getenv("OAUTH_TOKEN_TIMEOUT", "0.6"))

# Single-session idle timeout (minutes). 0 or negative disables idle expiry.
SINGLE_SESSION_IDLE_TIMEOUT_MINUTES = int(os.getenv("SINGLE_SESSION_IDLE_TIMEOUT_MINUTES", "120"))
SINGLE_SESSION_TOUCH_INTERVAL_SECONDS = int(
    os.getenv("SINGLE_SESSION_TOUCH_INTERVAL_SECONDS", "30")
)
SINGLE_SESSION_PRESENCE_TOUCH_INTERVAL_SECONDS = int(
    os.getenv("SINGLE_SESSION_PRESENCE_TOUCH_INTERVAL_SECONDS", "15")
)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "api.query.metrics": {
            "handlers": ["console"],
            "level": os.getenv("API_QUERY_METRICS_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'ko-KR'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Large payload (problem create: template/testcase bundles) protection limits
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50 MB

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.User'

###########################################################################################################
SPECTACULAR_SETTINGS = {
    'COMPONENT_SPLIT_REQUEST': True,
}

# Celery
CELERY_REDIS_HOST = os.getenv("CELERY_REDIS_HOST", "redis")
CELERY_REDIS_PORT = int(os.getenv("CELERY_REDIS_PORT", "6379"))
CELERY_REDIS_DB = int(os.getenv("CELERY_REDIS_DB", "0"))
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL") or _build_redis_url(
    CELERY_REDIS_HOST,
    CELERY_REDIS_PORT,
    CELERY_REDIS_DB,
    REDIS_PASSWORD,
)
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND") or CELERY_BROKER_URL
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = False

PENDING_SUBMISSION_TIMEOUT_MINUTES = int(
    os.getenv("PENDING_SUBMISSION_TIMEOUT_MINUTES", "15")
)
PENDING_SUBMISSION_MAX_AGE_DAYS = int(
    os.getenv("PENDING_SUBMISSION_MAX_AGE_DAYS", "7")
)
PENDING_SUBMISSION_CRON_SCHEDULE = (
    os.getenv("PENDING_SUBMISSION_CRON_SCHEDULE", "*/5 * * * *").strip()
    or "*/5 * * * *"
)
PENDING_SUBMISSION_CRON_LOCK_TIMEOUT_SECONDS = int(
    os.getenv("PENDING_SUBMISSION_CRON_LOCK_TIMEOUT_SECONDS", "240")
)
PENDING_SUBMISSION_CRON_HEARTBEAT_PATH = (
    os.getenv("PENDING_SUBMISSION_CRON_HEARTBEAT_PATH", "/tmp/pending_cleanup.log").strip()
    or "/tmp/pending_cleanup.log"
)
CRONTAB_COMMAND_PREFIX = ". /tmp/backend-cron-env.sh; "

CRONJOBS = [
    (
        PENDING_SUBMISSION_CRON_SCHEDULE,
        "instructor.pending_cleanup.run_stale_pending_cleanup_job",
    ),
]
