// This file is auto-generated by @hey-api/openapi-ts

export type TokenRefreshRequest = {
    refreshToken?: string;
};

export type TokenRefreshResponse = {
    accessToken?: string;
    refreshToken?: string;
};

export type LogoutRequest = {
    accessToken?: string;
    refreshToken?: string;
};

export type LoginRequest = {
    email?: string;
    password?: string;
};

export type LoginResponse = {
    accessToken?: string;
    refreshToken?: string;
};

export type UserInfoResponse = {
    email?: string;
    roles?: Array<string>;
    username?: string;
};

export type RefreshTokenData = {
    /**
     * Refresh token to generate new tokens
     */
    body: TokenRefreshRequest;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type RefreshTokenErrors = {
    /**
     * Invalid or expired refresh token
     */
    400: string;
};

export type RefreshTokenError = RefreshTokenErrors[keyof RefreshTokenErrors];

export type RefreshTokenResponses = {
    /**
     * Successfully refreshed tokens
     */
    200: TokenRefreshResponse;
};

export type RefreshTokenResponse = RefreshTokenResponses[keyof RefreshTokenResponses];

export type LogoutUserData = {
    /**
     * Refresh token to invalidate
     */
    body: LogoutRequest;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutUserErrors = {
    /**
     * Invalid refresh token
     */
    400: string;
};

export type LogoutUserError = LogoutUserErrors[keyof LogoutUserErrors];

export type LogoutUserResponses = {
    /**
     * Successfully logged out
     */
    200: {
        [key: string]: unknown;
    };
};

export type LogoutUserResponse = LogoutUserResponses[keyof LogoutUserResponses];

export type AuthenticateUserData = {
    /**
     * Email and password for authentication
     */
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthenticateUserErrors = {
    /**
     * Bad Request
     */
    400: string;
    /**
     * Invalid credentials
     */
    401: string;
};

export type AuthenticateUserError = AuthenticateUserErrors[keyof AuthenticateUserErrors];

export type AuthenticateUserResponses = {
    /**
     * Successfully authenticated
     */
    200: LoginResponse;
};

export type AuthenticateUserResponse = AuthenticateUserResponses[keyof AuthenticateUserResponses];

export type GetUserInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetUserInfoErrors = {
    /**
     * Unauthorized - Invalid or missing access token
     */
    401: string;
};

export type GetUserInfoError = GetUserInfoErrors[keyof GetUserInfoErrors];

export type GetUserInfoResponses = {
    /**
     * Successfully retrieved user information
     */
    200: UserInfoResponse;
};

export type GetUserInfoResponse = GetUserInfoResponses[keyof GetUserInfoResponses];

export type IndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type IndexResponses = {
    /**
     * OK
     */
    200: string;
};

export type IndexResponse = IndexResponses[keyof IndexResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};